# Generated by Django 2.2.8 on 2020-01-31 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasarelas', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=16, help_text='Porcentaje: Ej. 16%', max_digits=15)),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(blank=True, choices=[('Pendiente de Pago', 'Pendiente de Pago'), ('Pagada', 'Pagada'), ('En Revisión', 'En Revisión'), ('Transferida', 'Transferida'), ('Cancelada', 'Cancelada')], max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_facturas', to='empresa.Empresa')),
                ('forma_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formapago_facturas', to='pasarelas.FormaPago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
